#!/bin/bash

# 2013-09-19 14:33:16,Human,Hunter,Male,Saldaea,16,14,12,15,18

# download the latest stats
wget -O stats.csv http://wotmad.herokuapp.com/stats/export/ || exit 1
header=$(head -1 stats.csv)
sed -i 1d stats.csv

# figure out what's there
mapfile -t factions < <(cut -d, -f2 stats.csv | sort | uniq)
mapfile -t classes < <(cut -d, -f3 stats.csv | sort | uniq)
mapfile -t homelands < <(cut -d, -f5 stats.csv | sort | uniq)

# separate by faction/class/homeland
IFS=,
for faction in ${factions[@]}; do
	[[ ! -d $faction ]] && mkdir $faction
	for class in ${classes[@]}; do
		[[ ! -d $faction/$class ]] && mkdir $faction/$class
		for homeland in ${homelands[@]}; do
			echo "$header" > "$faction/$class/$homeland.csv"
			# male/female stats are supposedly the same nowadays
			grep ",$faction,$class,\(Male\|Female\),$homeland," stats.csv >> "$faction/$class/$homeland.csv" || rm "$faction/$class/$homeland.csv"
		done
	done
done



